[config]
contrast = 0

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar.css'
output_path = '~/.config/waybar/colors.css'
# post_hook = 'pkill -SIGUSR2 waybar'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.config/rofi/theme/colors.rasi'

# [templates.mako]
# input_path = '~/.config/matugen/templates/mako.conf'
# output_path = '~/.config/mako/colors.conf'
# post_hook = 'makoctl reload'

[templates.niri]
input_path = '~/.config/matugen/templates/niri.kdl'
output_path = '~/.config/niri/layout.kdl'
post_hook = 'niri msg action load-config-file'

[templates.swaync]
input_path = '~/.config/matugen/templates/swaync.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'swaync-client -rs &> /dev/null'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk3.css'
output_path = '~/.themes/adw-gtk3/gtk-3.0/colors.css'

[templates.gtk3-dark]
input_path = '~/.config/matugen/templates/gtk3-dark.css'
output_path = '~/.themes/adw-gtk3-dark/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk4.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.kvantum_kvconfig]
input_path = '~/.config/matugen/templates/kvantum.kvconfig'
output_path = '~/.config/Kvantum/matugen/matugen.kvconfig'

[templates.kvantum_svg]
input_path = '~/.config/matugen/templates/kvantum.svg'
output_path = '~/.config/Kvantum/matugen/matugen.svg'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.fcitx5_highlight]
input_path = '~/.config/matugen/templates/fcitx5/highlight.svg'
output_path = '~/.local/share/fcitx5/themes/matugen/highlight.svg'

[templates.fcitx5_panel]
input_path = '~/.config/matugen/templates/fcitx5/panel.svg'
output_path = '~/.local/share/fcitx5/themes/matugen/panel.svg'

[templates.fcitx5_config]
input_path = '~/.config/matugen/templates/fcitx5/theme.conf'
output_path = '~/.local/share/fcitx5/themes/matugen/theme.conf'
post_hook= 'dbus-send --type=method_call --dest=org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.ReloadAddonConfig string:"classicui"'
