[colors]
background = '#22272e'
foreground = '#adbac7'

cursor_bg = '#adbac7'
cursor_border = '#adbac7'
cursor_fg = '#22272e'

selection_bg = '#2e4c77'
selection_fg = '#adbac7'

split = "#539bf5"
compose_cursor = "#c93c37"
scrollbar_thumb = "#292e42"

ansi = [
  '#545d68',
  '#f47067',
  '#57ab5a',
  '#c69026',
  '#539bf5',
  '#b083f0',
  '#39c5cf',
  '#909dab',
]
brights = [
  '#636e7b',
  '#ff938a',
  '#6bc46d',
  '#daaa3f',
  '#6cb6ff',
  '#dcbdfb',
  '#56d4dd',
  '#cdd9e5',
]


[colors.tab_bar]
inactive_tab_edge = "#1f2335"
background = "#22272e"

[colors.tab_bar.active_tab]
fg_color = "#1f2335"
bg_color = "#539bf5"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#909dab" # a shadow grey
bg_color = "#22272e"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#6cb6ff" # a lighter main color
bg_color = "#22272e"
italic = true

[colors.tab_bar.new_tab_hover]
fg_color = "#22272e"
bg_color = "#6cb6ff"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#6cb6ff"
bg_color = "#22272e"

[metadata]
name = "github"
