[colors]
foreground = "#dcd7ba"
background = "#1f1f28"

cursor_bg = "#c8c093"
cursor_fg = "#1f1f28"
cursor_border = "#c8c093"

selection_fg = "#c8c093"
selection_bg = "#2d4f67"

scrollbar_thumb = "#16161d"
split = "#16161d"

ansi = [
  "#090618",
  "#c34043",
  "#76946a",
  "#c0a36e",
  "#7e9cd8",
  "#957fb8",
  "#6a9589",
  "#c8c093",
]
brights = [
  "#727169",
  "#e82424",
  "#98bb6c",
  "#e6c384",
  "#7fb4ca",
  "#938aa9",
  "#7aa89f",
  "#dcd7ba",
]

[colors.tab_bar]
inactive_tab_edge = "#1f1f28"
background = "#1f1f28"

[colors.tab_bar.active_tab]
bg_color = "#957fb8"
fg_color = "#1f1f28"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#727169"
bg_color = "#16161d"
intensity = "Normal"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#938aa9"
bg_color = "#1f1f28"
italic = true

[colors.tab_bar.new_tab]
fg_color = "#957fb8"
bg_color = "#16161d"

[colors.tab_bar.new_tab_hover]
bg_color = "#957fb8"
fg_color = "#1f1f28"
intensity = "Bold"

[colors.indexed]
16 = "#ffa066"
17 = "#ff5d62"
