[metadata]
name = "material"

[colors]
foreground = "#8C8B8B"
background = "#212121"
cursor_bg = "#FFCC00"
cursor_border = "#FFCC00"
cursor_fg = "#8C8B8B"
compose_cursor = '#FF9800'
selection_bg = "#404040"
selection_fg = "#8C8B8B"
scrollbar_thumb = "#343434"
split = "#343434"
ansi = [
  "#000000",
  "#DC6068",
  "#ABCF76",
  "#E6B455",
  "#6E98EB",
  "#B480D6",
  "#71C6E7",
  "#EEFFFF",
]
brights = [
  "#000000",
  "#F07178",
  "#C3E88D",
  "#FFCB6B",
  "#82AAFF",
  "#C792EA",
  "#89DDFF",
  "#EEFFFF",
]

[colors.indexed]
16 = "#FF9CAC"
17 = "#80CBC4"

[colors.tab_bar]
background = "#212121"
inactive_tab_edge = "#131a24"
inactive_tab_edge_hover = "#212e3f"

[colors.tab_bar.active_tab]
bg_color = "#8C8B8B"
fg_color = "#212121"
intensity = "Bold"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#1A1A1A"
fg_color = "#8C8B8B"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#1A1A1A"
fg_color = "#8C8B8B"
intensity = "Normal"
italic = true
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#1A1A1A"
fg_color = "#8C8B8B"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#8C8B8B"
fg_color = "#212121"
intensity = "Bold"
italic = false
strikethrough = false
underline = "None"
