# Nordic Colorscheme for Wezterm.
# Based on https://github.com/AlexvZyl/nordic.nvim
# Author: @kuntau

[colors]
foreground = "#D8DEE9"
background = "#242933"
cursor_bg = "#D8DEE9"
cursor_border = "#D8DEE9"
cursor_fg = "#242933"
selection_fg = "#D8DEE9"
selection_bg = "#2E3440"

ansi = [
  "#191D24",
  "#BF616A",
  "#A3BE8C",
  "#EBCB8B",
  "#81A1C1",
  "#B48EAD",
  "#8FBCBB",
  "#D8DEE9",
]
brights = [
  "#3B4252",
  "#D06F79",
  "#B1D196",
  "#F0D399",
  "#88C0D0",
  "#C895BF",
  "#93CCDC",
  "#E5E9F0",
]

[colors.tab_bar]
inactive_tab_edge = "#242933"
background = "#242933"

[colors.tab_bar.active_tab]
fg_color = "#242933"
bg_color = "#F0D399"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#D8DEE9"
bg_color = "#2E3440"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#242933"
fg_color = "#F0D399"
italic = true

[colors.tab_bar.new_tab_hover]
fg_color = "#242933"
bg_color = "#F0D399"
intensity = "Bold"

[colors.tab_bar.new_tab]
bg_color = "#242933"
fg_color = "#F0D399"
