[env]
TERM = "xterm-256color"

[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/github_dark_dimmed.toml"]

[window]
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 120
lines = 30

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[selection]
save_to_clipboard = true

# ctl + click to open links
[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
mouse.enabled = true
mouse.mods = "Control"
post_processing = true
persist = false
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"

[mouse]
bindings = [{ mouse = "Right", mode = "~Vi|~Search", action = "Paste" }]
