# ~/.config/tmux/tmux.conf

set -g escape-time 50  # for wsl

# use the same color scheme as terminal
set-option -sa terminal-overrides ",xterm*:Tc"
# mouse support
set -g mouse on

# change prefix key mapping
unbind C-b
set -g prefix M-b  # Alt-b
bind M-b send-prefix

# start windows and panes from 1 but 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1

# yank like vim
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# open new panels in current path but home
bind = split-window -v -c "#{pane_current_path}"
bind - split-window -h -c "#{pane_current_path}"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'  # navigate as vim
set -g @plugin 'tmux-plugins/tmux-yank'  # copy to clipboard

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
