background-color={{colors.surface_container.default.hex}}
text-color={{colors.tertiary.default.hex}}
border-color={{colors.outline.default.hex}}
progress-color={{colors.primary.default.hex}}

[urgency=high]
border-color={{colors.error.default.hex}}
