# +----------------------------------------------------------+
# |                         代理配置                         |
# +----------------------------------------------------------+

# 可以添加单个代理服务器
proxies:
  - name: "🎯 直连"
    type: direct
    udp: true

# provider 锚点
p: &p
  type: http
  interval: 86400
  health-check:
    enable: true
    url: https://www.google.com/generate_204
    interval: 21600

# url 里填写自己的订阅,名称不能重复
proxy-providers:
  main:
    <<: *p
    url: ""
  fallback1:
    <<: *p
    url: ""
    override:
      additional-prefix: "[备]"
  fallback2:
    <<: *p
    url: ""
    override:
      additional-prefix: "[自]"

# +----------------------------------------------------------+
# |                      Clash 基础设置                      |
# +----------------------------------------------------------+

allow-lan: true
mode: rule
log-level: info
ipv6: true
find-process-mode: strict
external-controller: 127.0.0.1:9090
external-ui: ui # 前端路径 /path/to/clash/config/ui
external-ui-url: "https://github.com/Zephyruso/zashboard/releases/latest/download/dist-firasans-only.zip"
unified-delay: true # 计算延迟时是否去除握手等额外开销
profile: # 缓存配置
  store-selected: true # 保存 API 控制的更改
  store-fake-ip: true # 保存 fake-ip 映射表
tcp-concurrent: true
geodata-mode: true # geo 配置
geo-auto-update: true
geo-update-interval: 24
geox-url: # 自定义GEO下载地址, 启用cdn加速下载
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
  asn: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"

# +----------------------------------------------------------+
# |                         DNS 设置                         |
# +----------------------------------------------------------+

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: true # 如果需要使用 box for magisk 的热点共享代理，需要设置为 false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16 # clash 以此 IP 段发送 fake-ip 映射
  fake-ip-range6: fdfe:dcba:9876::1/64
  fake-ip-filter: # fakeip 分流，让国内域名走 real-ip，其余走 fake-ip
    - RULE-SET,private_domain,real-ip
    - RULE-SET,fakeip_filter,real-ip
    - RULE-SET,qiufen_ad_doamin,real-ip # 传递给 real-ip 实现不解析
    - RULE-SET,category_ads_domain,real-ip
    - RULE-SET,category_porn_domain,real-ip
    - RULE-SET,blacklist,real-ip
    - RULE-SET,google_domain,fake-ip
    - RULE-SET,microsoft_domain,fake-ip
    - RULE-SET,geolocation-!cn,fake-ip
    - RULE-SET,cn_domain,real-ip
    - MATCH,fake-ip
  fake-ip-filter-mode: rule
  default-nameserver: # 用于解析 DNS 服务器, 必须为 IP 且可访问
    - 223.5.5.5
    - 119.29.29.29
  nameserver-policy: # real-ip 的分流规则，国内外域名分流
    "sub.skky.indevs.in": # 国内可访问的境外 dns 解析订阅链接
      - 8.8.8.8
    "+.cloudflare-ech.com":
      - https://dns.alidns.com/dns-query
    "rule-set:blacklist,qiufen_ad_doamin":
      - rcode://success # 通过不解析 dns 拦截
    "geosite:category-ads-all,category-porn":
      - rcode://success
    "rule-set:private_domain,fakeip_filter":
      - https://dns.alidns.com/dns-query
    "rule-set:google_domain,microsoft_domain,geolocation-!cn":
      - https://8.8.8.8/dns-query#🥤 默认
    "geosite:cn":
      - https://dns.alidns.com/dns-query
  proxy-server-nameserver: # 用于解析代理节点的域名
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  nameserver: # 默认域名解析，用于兜底 nameserver-policy 无法匹配的域名
    - https://8.8.8.8/dns-query#🥤 默认&ecs=114.114.114.114/24&ecs-override=true

# +----------------------------------------------------------+
# |       域名嗅探，从流量中获取域名，从而使用域名规则       |
# +----------------------------------------------------------+

sniffer:
  enable: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"

# +----------------------------------------------------------+
# |                         入站配置                         |
# +----------------------------------------------------------+

mixed-port: 7890
tproxy-port: 9898

## tun赋权  ##
# Linux: sudo setcap cap_net_bind_service,cap_net_admin=+ep /path/to/clash
# ref: https://github.com/zzzgydi/clash-verge/issues/182
#
# Windows: 以管理员身份运行
tun:
  enable: false # 默认关闭
  device: mihomo
  stack: mixed
  dns-hijack:
    - "any:53"
  auto-route: true
  auto-detect-interface: true

# +----------------------------------------------------------+
# |                         代理分组                         |
# +----------------------------------------------------------+

FilterHK: &FilterHK "^(?=.*(?i)(港|🇭🇰|HK|Hong|HKG)).*$"
FilterSG: &FilterSG "^(?=.*(?i)(坡|🇸🇬|SG|Sing|SIN|XSP)).*$"
FilterJP: &FilterJP "^(?=.*(?i)(日|🇯🇵|JP|Japan|NRT|HND|KIX|CTS|FUK)).*$"
FilterKR: &FilterKR "^(?=.*(?i)(韩|🇰🇷|韓|首尔|南朝鲜|KR|KOR|Korea|South)).*$"
FilterUS: &FilterUS "^(?=.*(?i)(美|🇺🇸|US|USA|SJC|JFK|LAX|ORD|ATL|DFW|SFO|MIA|SEA|IAD)).*$"
FilterTW: &FilterTW "^(?=.*(?i)(台|🇼🇸|🇹🇼|TW|tai|TPE|TSA|KHH)).*$"
FilterOT: &FilterOT "^(?!.*(港|🇭🇰|HK|Hong|HKG|坡|🇸🇬|SG|Sing|SIN|XSP|日|🇯🇵|JP|Japan|NRT|HND|KIX|CTS|FUK|韩|🇰🇷|韓|首尔|南朝鲜|KR|KOR|Korea|South|美|🇺🇸|US|USA|SJC|JFK|LAX|ORD|ATL|DFW|SFO|MIA|SEA|IAD|台|🇼🇸|🇹🇼|TW|tai|TPE|TSA|KHH)).*$"

Exclude: &Exclude '^(\[备\]|\[自\]).*$'

default: &default
  type: select
  proxies:
    - 🥤 默认
    - 🇭🇰 香港
    - 🇹🇼 台湾
    - 🇯🇵 日本
    - 🇰🇷 韩国
    - 🇸🇬 新加坡
    - 🇺🇸 美国
    - 🌏 其它地区
    - 🎯 直连
    - 🚀 全部节点
    - ♻ 自动选择
direct: &direct
  type: select
  proxies:
    - 🎯 直连
    - 🥤 默认
    - 🇭🇰 香港
    - 🇹🇼 台湾
    - 🇯🇵 日本
    - 🇰🇷 韩国
    - 🇸🇬 新加坡
    - 🇺🇸 美国
    - 🌏 其它地区
    - 🚀 全部节点
    - ♻ 自动选择

proxy-groups:
  - name: 🥤 默认
    type: select
    proxies:
      - 🚀 全部节点
      - ♻ 自动选择
      - 🎯 直连
      - 🇭🇰 香港
      - 🇹🇼 台湾
      - 🇯🇵 日本
      - 🇰🇷 韩国
      - 🇸🇬 新加坡
      - 🇺🇸 美国
      - 🌏 其它地区

  - name: 🚀 全部节点
    type: select
    proxies:
      - ✈️ 主订阅
      - 🛩️ 备用订阅
      - 🛩️ 自建节点
  - name: ✈️ 主订阅
    type: select
    exclude-filter: *Exclude
    include-all-providers: true
  - name: 🛩️ 备用订阅
    type: select
    filter: '^\[备\].*$'
    include-all-providers: true
  - name: 🛩️ 自建节点
    type: select
    filter: '^\[自\].*$'
    include-all: true

  - name: ♻ 自动选择
    type: url-test
    interval: 21600
    lazy: true
    url: "https://www.google.com/generate_204"
    hidden: true
    exclude-filter: *Exclude
    include-all-providers: true
    tolerance: 10

  - name: 🇭🇰 香港
    type: select
    filter: *FilterHK
    exclude-filter: *Exclude
    include-all-providers: true
  - name: 🇹🇼 台湾
    type: select
    filter: *FilterTW
    exclude-filter: *Exclude
    include-all-providers: true
  - name: 🇯🇵 日本
    type: select
    filter: *FilterJP
    exclude-filter: *Exclude
    include-all-providers: true
  - name: 🇰🇷 韩国
    type: select
    filter: *FilterKR
    exclude-filter: *Exclude
    include-all-providers: true
  - name: 🇸🇬 新加坡
    type: select
    filter: *FilterSG
    exclude-filter: *Exclude
    include-all-providers: true
  - name: 🇺🇸 美国
    type: select
    filter: *FilterUS
    exclude-filter: *Exclude
    include-all-providers: true
  - name: 🌏 其它地区
    type: select
    filter: *FilterOT
    exclude-filter: *Exclude
    include-all-providers: true

  - name: 🍮 Github
    <<: *default
  - name: 🥛 Spotify
    <<: *default
  - name: 🫙 Microsoft
    <<: *default
  - name: 🧊 Google
    <<: *default
  - name: 🍭 Telegram
    <<: *default
  - name: 🧋 YouTube
    <<: *default
  - name: 🍡 Tracker
    <<: *direct
  - name: ⭐ 其他非大陆
    <<: *default
  - name: 🇨🇳 国内
    <<: *direct
  - name: 📢 谷歌FCM
    <<: *direct
  - name: 🐟 漏网之鱼
    <<: *default

# +----------------------------------------------------------+
# |                         规则分流                         |
# +----------------------------------------------------------+

rules:
  # 域名规则
  - GEOIP,lan,🎯 直连,no-resolve
  - RULE-SET,private_domain,🎯 直连
  - RULE-SET,fakeip_filter,🎯 直连
  - RULE-SET,qiufen_ad_doamin,REJECT
  - RULE-SET,category_ads_domain,REJECT
  - RULE-SET,category_porn_domain,REJECT
  - RULE-SET,blacklist,REJECT
  - RULE-SET,direct_apps,🎯 直连
  - RULE-SET,google_fcm,📢 谷歌FCM
  - RULE-SET,github_domain,🍮 Github
  - RULE-SET,spotify_domain,🥛 Spotify
  - RULE-SET,microsoft_domain,🫙 Microsoft
  - RULE-SET,google_domain,🧊 Google
  - RULE-SET,telegram_domain,🍭 Telegram
  - RULE-SET,youtube_domain,🧋 YouTube
  - RULE-SET,tracker_domain,🍡 Tracker
  - RULE-SET,geolocation-!cn,⭐ 其他非大陆
  - RULE-SET,cn_domain,🇨🇳 国内
  # IP规则, 如果域名规则不匹配则进入IP规则, 此时会使用Clash配置的DNS规则解析IP
  - RULE-SET,google_ip,🧊 Google
  - RULE-SET,telegram_ip,🍭 Telegram
  - RULE-SET,cn_ip,🇨🇳 国内
  # 未匹配兜底
  - MATCH,🐟 漏网之鱼

# +----------------------------------------------------------+
# |                          规则集                          |
# +----------------------------------------------------------+

# IP 规则集
ip: &ip
  type: http
  interval: 86400
  behavior: ipcidr
  format: yaml
mrs: &mrs
  type: http
  interval: 86400
  behavior: domain
  format: mrs
# 域名规则集
domain: &domain
  type: http
  interval: 86400
  behavior: domain
  format: yaml
mrsip: &mrsip
  type: http
  interval: 86400
  behavior: ipcidr
  format: mrs

rule-providers:
  private_domain:
    <<: *mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"
  github_domain:
    <<: *mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"
  spotify_domain:
    <<: *mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.mrs"
  microsoft_domain:
    <<: *mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"
  google_domain:
    <<: *mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"
  youtube_domain:
    <<: *mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"
  telegram_domain:
    <<: *mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"
  tracker_domain:
    <<: *mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tracker.mrs"
  google_fcm:
    <<: *domain
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleFCM.yaml"
  geolocation-!cn:
    <<: *mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"
  qiufen_ad_doamin:
    <<: *domain
    url: "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash.yaml"
  category_ads_domain:
    <<: *mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ads.mrs"
  category_porn_domain:
    <<: *mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-porn.mrs"
  cn_domain:
    <<: *mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"
  google_ip:
    <<: *mrsip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"
  telegram_ip:
    <<: *mrsip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"
  cn_ip:
    <<: *mrsip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"
  fakeip_filter:
    <<: *mrs
    url: "https://raw.githubusercontent.com/zhiim/dotfiles/master/dot_config/mihomo/rule_set/fakeip_filter.mrs"
  blacklist:
    <<: *mrs
    url: "https://raw.githubusercontent.com/zhiim/dotfiles/master/dot_config/mihomo/rule_set/blacklist.mrs"
  direct_apps:
    type: inline
    behavior: classical
    payload:
      # 为特定进程设置直连
      - PROCESS-PATH,/usr/bin/linuxqq
      - PROCESS-PATH,/opt/wechat/wechat
      - PROCESS-PATH,/usr/bin/krdc
      - PROCESS-PATH-REGEX,\/tmp\/\.mount_linux.*\/qq
      - PROCESS-PATH-REGEX,\/opt\/wechat\/.*
