#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=15

start_service() {
    if ! command -v setcap >/dev/null 2>&1; then
        echo "setcap not found，install libcap-bin first" >&2
        return 1
    fi

    setcap 'cap_net_admin,cap_net_bind_service,cap_net_raw,cap_sys_ptrace,cap_dac_read_search+ep' /usr/bin/mihomo || {
        echo "mihomo capabilities set failed" >&2
        return 1
    }

    procd_open_instance
    procd_set_param command /usr/bin/mihomo -d /usr/share/mihomo
    procd_set_param user "mihomo"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn
    procd_close_instance
}
